### ISSUE TITLE
aCar Converter does not work anymore

### ISSUE THREAD

**Issue by chrisonline** [Programistyk/FuelioImport#1]
If I upload my file I get always this screen:
![fuelio](https://cloud.githubusercontent.com/assets/2077218/15070639/c3f8f0d6-1385-11e6-808a-335fe23fe4c3.png)

**Comment by mrblur** [comment]
Hi,

It seems, that after move from php5 to php7, our server did not install php-zip back.
Could you please try again?

**Comment by chrisonline** [comment]
No the same error.

**Comment by mrblur** [comment]
Should be alright now. At least worked for me ;)

**Comment by chrisonline** [comment]
Yes now it is working again... Was a cache problem on my site.

**Comment by mrblur** [comment]
I'm happy that its working, closing then.
