### ISSUE TITLE
Import from FuelLog Error

### ISSUE THREAD

**Issue by besworkman** [Programistyk/FuelioImport#10]
This is the error I get when importing from FuelLog to Fuelio. I had to convert the csv to txt, that is also attached.

Warning: DateTime::modify(): Failed to parse time string (P1M) at position 1 (1): Unexpected character in /app/lib/fuelioimporter/providers/fuellogprovider.class.php on line 415

Warning: Cannot modify header information - headers already sent by (output started at /app/lib/fuelioimporter/providers/fuellogprovider.class.php:415) in /app/web/convert.php on line 48

Warning: Cannot modify header information - headers already sent by (output started at /app/lib/fuelioimporter/providers/fuellogprovider.class.php:415) in /app/web/convert.php on line 49
## Vehicle,,,,,,,,,,,,,, Name,Description,DistUnit,FuelUnit,ConsumptionUnit,ImportCSVDateFormat,VIN,Insurance,Plate,Make,Model,Year,TankCount,Tank1Type,Tank2Type,Active "Toyota Rav4 Hybrid",,1,1,1,dd.MM.yyyy,,,,,,,1,,,1 ## Log,,,,,,,,,,,,, Data,Odo(km),Fuel(litres),Full,Price(optional),l/100km(optional),latitude(optional),longitude(optional),City(optional),Notes(optional),Missed,TankNumber,FuelType,VolumePrice 01.09.2018,61,0,1,,,,,,,0,1,,0 15.09.2018,350,9.579,1,,,,,,,0,1,,3.099 23.09.2018,688,10.09,1,,,,,,,0,1,,2.999 09.10.2018,1047,11.956,1,,,,,,,0,1,,2.979 27.10.2018,1397,12.187,1,,,,,,,0,1,,2.899 12.11.2018,1658,9.416,1,,,,,,,0,1,,2.799 01.12.2018,1977,11.145,1,,,,,,,0,1,,2.539 07.12.2018,2149,6.085,1,,,,,,,0,1,,2.459 21.12.2018,2448,11.069,1,,,,,,,0,1,,2.079 05.01.2019,2769,10.649,1,,,,,,,0,1,,2.289 13.01.2019,3020,9.251,1,,,,,,,0,1,,2.499 21.01.2019,3251,8.427,1,,,,,,,0,1,,2.499 02.02.2019,3494,9.514,1,,,,,,,0,1,,2.289 16.02.2019,3802,11.143,1,,,,,,,0,1,,2.57 02.03.2019,4090,10.594,1,,,,,,,0,1,,2.479 09.03.2019,4377,10.88,1,,,,,,,0,1,,2.65 24.03.2019,4705,10.921,1,,,,,,,0,1,,2.799 31.03.2019,4940,8.448,1,,,,,,,0,1,,275.9 06.04.2019,5075,4.335,1,,,,,,,0,1,,2.539 20.04.2019,5380,10.397,1,,,,,,,0,1,,2.679 05.05.2019,5659,8.92,1,,,,,,,0,1,,2.899 19.05.2019,5900,8.119,1,,,,,,,0,1,,3.99 08.06.2019,6193,9.836,1,,,,,,,0,1,,2.599 16.06.2019,6371,5.548,1,,,,,,,0,1,,2.659 29.06.2019,6655,9.624,1,,,,,,,0,1,,25.69 07.07.2019
[2020-04-21.txt](https://github.com/Programistyk/FuelioImport/files/4523643/2020-04-21.txt)
,6850,6.262,1,,,,,,,0,1,,2.819 20.07.2019,7095,8.879,1,,,,,,,0,1,,2.939 10.08.2019,7388,10.243,1,,,,,,,0,1,,2.899 25.08.2019,7650,9.13,1,,,,,,,0,1,,2.679 14.09.2019,7981,11.094,1,,,,,,,0,1,,2.639 21.09.2019,8168,5.92,1,,,,,,,0,1,,2.799 13.10.2019,8457,10.424,1,,,,,,,0,1,,2.469 02.11.2019,8772,11.56,1,,,,,,,0,1,,2.699 16.11.2019,9035,8.897,1,,,,,,,0,1,,2.499 23.11.2019,9226,7,1,,,,,,,0,1,,2.799 07.12.2019,9534,10.963,1,,,,,,,0,1,,267.9 22.12.2019,9819,11.358,1,,,,,,,0,1,,2.599 27.12.2019,10137,10.426,1,,,,,,,0,1,,2.659 11.01.2020,10418,10.195,1,,,,,,,0,1,,2.799 18.01.2020,10685,9.99,1,,,,,,,0,1,,2.739 28.01.2020,10963,9.576,1,,,,,,,0,1,,2.499 11.02.2020,11245,10.385,1,,,,,,,0,1,,2.399 01.03.2020,11544,10.559,1,,,,,,,0,1,,2.499 08.03.2020,11842,10.057,1,,,,,,,0,1,,24.13 ## CostCategories,,,,,,,,,,, CostTypeID,Name,priority 50,"FuelLog Import",0, ## Costs,,,,,,,,,,,,,,, CostTitle,Date,Odo,CostTypeID,Notes,Cost,flag,idR,read,RemindOdo,RemindDate,isTemplate,RepeatOdo,RepeatMonths,isIncome,UniqueId "Down Payment",06.09.2018,0,50,,1500,0,0,1,0,01.01.2011,0,0,0,0, "Monthly payment",06.10.2018,0,50,,375.77,0,0,1,0,06.10.2018,0,0,1,0,

**Comment by besworkman** [comment]
Why was this closed without resolution?

**Comment by mrblur** [comment]
It was closed with commit 50e22cd fixing warning with date formatting and making fuellog convert fine.
Your file is messed up by excel or other spreadsheet app, but after cleaning it also converts fine.

I don't see any other resolution to provide.
