### ISSUE TITLE
413 Request Entity too large

### ISSUE THREAD

**Issue by fabella** [Programistyk/FuelioImport#11]
I'm trying to use acar converter but I'm getting 413 status code. The file size is about 2303KB.

![image](https://user-images.githubusercontent.com/8219420/94879641-6d108680-0426-11eb-82fd-6703feb166ba.png)

**Comment by mrblur** [comment]
Hi @fabella 
Sorry for that, human error, had to rebuild webserver config and forgot about increasing upload limit.
Should be fixed now.

Best regards,
Kamli Kamiński
