### ISSUE TITLE
Missing last refuel record from Drivvio import

### ISSUE THREAD

**Issue by 7eXx** [Programistyk/FuelioImport#15]
When importing csv generated from drivvio, the output generated has the last refuel record that is missing.

**Comment by mrblur** [comment]
hey @7eXx !

I couldn't reproduce this on the drivvo files I've got. Can you send me your file and point to the missing record?

**Comment by 7eXx** [comment]
This file is the one exported from Drivvo:  
[20220601_162723_DRIVVO.csv](https://github.com/Programistyk/FuelioImport/files/8815175/20220601_162723_DRIVVO.csv)
The other one is converted using [https://github.com/Programistyk/FuelioImport]()  
[FuelioBackup-Drivvo-Car.csv](https://github.com/Programistyk/FuelioImport/files/8815185/FuelioBackup-Drivvo-Car.csv)

Looking carefully, it can see that the last record on top is missing from the original file.

**Comment by mrblur** [comment]
Hey @7eXx !
Sorry for late response. I have fixed parsing Drivvo file so that we no longer assume internal cursor position while looking for a specific file part.

You can try converting your file now :)
Don't hesitate to reopen or fill another issue if the problem remains or you find something else.

**Comment by 7eXx** [comment]
> Hey @7eXx !
> Sorry for late response. I have fixed parsing Drivvo file so that we no longer assume internal cursor position while looking for a specific file part.
> 
> You can try converting your file now :)
> Don't hesitate to reopen or fill another issue if the problem remains or you find something else.

Thank you very much... I will test it as soon as possible

**Comment by 7eXx** [comment]
Tested... Work perfectly... Thank you very much...
