### ISSUE TITLE
aCar ABP Converter issue

### ISSUE THREAD

**Issue by Myrddid** [Programistyk/FuelioImport#17]
Hi, I tried to convert a backup from aCar but I've got error "413 Request entity too large". abp file is almost 24MB, is it possible to increase max file size?

Thanks

**Comment by mrblur** [comment]
Hi @Myrddid sorry for that late response.

I would rather not increase the upload limit above current 20M.

You should be able to quick and dirty checkout and run the app locally with no limits.
