### ISSUE TITLE
App unavailable

### ISSUE THREAD

**Issue by gotens87** [Programistyk/FuelioImport#18]
http://fuelio.programistyk.pl/ is timing out as unreachable.

**Comment by mrblur** [comment]
Thank you, thanks to my service provider, server went down. I have not migrated this service to new location yet.

I'll close this issue once website is back online.

**Comment by mrblur** [comment]
Hi @gotens87. Sorry, it took me almost two months, but finally, the app is back up :)

In my defense, I had to wait over 6 weeks for the manufacturer to complete my order for the server motherboard. And I had to build the actual system from ground up.

It is now up and running, hosted from my home, so I expect no more shady actions from OVH.
