### ISSUE TITLE
Error: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by naonozawa** [Programistyk/FuelioImport#8]
When I try to convert an aCar ABP file, I get the "314 Request Entity Too Large" error. All of my .abp files appear to be 7.00 MB, is that too large?

**Comment by mrblur** [comment]
Hi,

Hosting service is not sponsored and was configured with some economical defaults, like 3MB upload size limit. I just upped that to be 10MB so you should be good now ;)
The app has no limits itself, only those of PHP and webserver it is running on.

7MB for an .abp seems like a huge file, given that it's a .zip archive containing text files. Did aCar started to include a photo gallery?

I am closing this, as it has nothing to do with the code itself and should be fixed now.

**Comment by naonozawa** [comment]
I opened up the abp and my vehicles.xml file is 10.7 MB.

I'm no longer getting the 413 error (thanks!) but am getting an SplFileObject message. Should I open up a new issue for this?
